name: CI

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - id: docker-publish
        name: Build and Push Docker Image
        uses: bitovi/github-actions-docker-publish@main
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          org_name: jgcarraro
          repo_name: teste2
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd app
            docker compose pull
            docker compose up --force-recreate -d